Repository pudding-tech/mikane, pull requests merged in 2023-09, with the labels that each got.

#293 chore: create backend build and deploy workflow
  .github/workflows/api-staging.yml
  .github/workflows/backend-build.yml
  .github/workflows/backend-deploy-release.yml
  .github/workflows/backend-deploy.yml
  .github/workflows/backend-test.yml
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  README.md
Labels: backend, chore

#295 Frontend testing
  app/mikane/src/app/pages/account/account.component.spec.ts
  app/mikane/src/app/pages/account/account.component.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.spec.ts
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.spec.ts
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.ts
  app/mikane/src/app/pages/account/user/user-settings.component.spec.ts
  app/mikane/src/app/shared/forms/validators/async-category-name.validator.spec.ts
  app/mikane/src/app/shared/forms/validators/async-email.validator.spec.ts
  app/mikane/src/app/shared/forms/validators/async-event-name.validator.spec.ts
  app/mikane/src/app/shared/forms/validators/async-phone.validator.spec.ts
  app/mikane/src/app/shared/forms/validators/async-username.validator.spec.ts
  app/mikane/src/app/shared/forms/validators/compare.validator.spec.ts
Labels: frontend, test

#296 feat: No resource message on mobile
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
Labels: frontend, improvement

#297 test: add test for feature components/directives
  app/mikane/src/app/features/confirm-dialog/confirm-dialog.component.spec.ts
  app/mikane/src/app/features/footer/footer.component.spec.ts
  app/mikane/src/app/features/footer/footer.component.ts
  app/mikane/src/app/features/menu/menu.component.spec.ts
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/features/mobile/category-item/category-item.component.spec.ts
  app/mikane/src/app/features/mobile/event-item/event-item.component.spec.ts
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.html
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.spec.ts
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.spec.ts
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.spec.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.spec.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.spec.ts
  app/mikane/src/app/features/split-button/split-button.component.spec.ts
  app/mikane/src/app/features/split-button/split-button.component.ts
Labels: frontend, test

#299 Frontend testing
  app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/services/auth/auth.service.spec.ts
  app/mikane/src/app/services/message/error/error-message.component.spec.ts
  app/mikane/src/app/services/message/success/success-message.component.spec.ts
  app/mikane/src/app/services/user/user.service.spec.ts
  app/mikane/src/app/services/user/user.service.ts
Labels: frontend, test

#301 Frontend testing
  app/mikane/.eslintrc.json
  app/mikane/src/app/pages/event-info/event-info.component.spec.ts
  app/mikane/src/app/pages/event-info/event-info.component.ts
  app/mikane/src/app/pages/participant/expense.datasource.spec.ts
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.spec.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
Labels: frontend, test

#303 feat: Filtering for payers and categories on expenses page
  app/mikane/.eslintrc.json
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
  app/mikane/src/app/services/message/success/success-message.component.ts
Labels: frontend, feature

#307 feat: Filtering for mobile
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.spec.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.html
  app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.scss
  app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.spec.ts
  app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.ts
  app/mikane/src/styles.scss
Labels: frontend, feature

#308 feat: Go to participant expenses (mobile)
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.spec.ts
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expense/expense.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
Labels: frontend, improvement
