Repository pudding-tech/mikane, pull requests merged in 2023-12, with the labels that each got.

#319 chore(angular): use new angular build system
  app/mikane/angular.json
  app/mikane/tsconfig.json
Labels: frontend, chore

#320 chore: Update backend testing
  .github/workflows/backend-deploy-release.yml
  .github/workflows/backend-test.yml
  .github/workflows/backend.yml
  server/Dockerfile
  server/package-lock.json
  server/package.json
  server/src/server.ts
  server/tests/authentication.test.ts
  server/tests/categories.test.ts
  server/tests/events.test.ts
  server/tests/expenses.test.ts
  server/tests/guestUsers.test.ts
  server/tests/resetDatabase.ts
  server/tests/setup.ts
  server/tests/users.test.ts
  server/tests/validation.test.ts
  server/vitest.config.ts
Labels: backend, chore

#321 feat: Super-admins - restrictions on managing guests
  app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.html
  app/mikane/src/app/pages/guests/guests.component.html
  app/mikane/src/app/pages/guests/guests.component.ts
  app/mikane/src/app/services/user/user.service.ts
  server/db_scripts/convert_guest_to_user.sql
  server/db_scripts/delete_guest_user.sql
  server/db_scripts/delete_user.sql
  server/db_scripts/edit_guest_user.sql
  server/db_scripts/edit_user.sql
  server/db_scripts/get_user.sql
  server/db_scripts/get_users.sql
  server/db_scripts/new_guest_user.sql
  server/db_scripts/new_user.sql
  server/db_scripts/schema/2.1-2.2_migrations.sql
  server/db_scripts/schema/db_schema.sql
  server/src/api.json
  server/src/api/authentication.ts
  server/src/api/guestUsers.ts
  server/src/db/dbGuestUsers.ts
  server/src/parsers/parseUsers.ts
  server/src/types/errorCodes.ts
  server/src/types/express-session.d.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/tests/guestUsers.test.ts
Labels: frontend, backend, feature

#322 Mobile: 'Remove user from event' button
  app/mikane/src/app/features/mobile/event-item/event-item.component.scss
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.scss
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/services/message/success/success-message.component.ts
Labels: frontend, improvement

#324 feat: Expenses info on category + prevent deletion of categories with expenses
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.scss
  app/mikane/src/app/features/mobile/category-item/category-item.component.spec.ts
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
  app/mikane/src/app/pages/category/category.component.spec.ts
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/services/category/category.service.ts
  server/db_scripts/add_user_to_category.sql
  server/db_scripts/delete_category.sql
  server/db_scripts/edit_category.sql
  server/db_scripts/edit_category_weighted_status.sql
  server/db_scripts/edit_user_weight.sql
  server/db_scripts/get_categories.sql
  server/db_scripts/new_category.sql
  server/db_scripts/remove_user_from_category.sql
  server/package-lock.json
  server/package.json
  server/src/db/dbCategories.ts
  server/src/parsers/parseCategories.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/tests/categories.test.ts
Labels: frontend, backend, feature

#325 feat: Scroll service, hide buttons when page is at bottom
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/services/scroll/scroll.service.spec.ts
  app/mikane/src/app/services/scroll/scroll.service.ts
Labels: frontend, feature

#327 Add backend deploy and frontend test deploy
  .github/workflows/backend-build.yml
  .github/workflows/backend-deploy.yml
  .github/workflows/backend.yml
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-bump.yml
  .github/workflows/frontend-deploy-release.yml
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-test.yml
  .github/workflows/frontend.yml
  app/mikane/angular.json
  app/mikane/package.json
  app/mikane/src/environments/environment.test.ts
  server/esbuild.config.mjs
  server/package-lock.json
  server/package.json
  server/src/api.json
Labels: frontend, backend, chore

#328 chore: rework bump and deploy workflows
  .github/workflows/backend-build.yml
  .github/workflows/backend.yml
  .github/workflows/bump.yml
  .github/workflows/deploy.yml
  .github/workflows/frontend.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: frontend, backend, chore

#329 fix: don't use dry run for snapshot deployment
  .github/workflows/backend-deploy-release.yml
  .github/workflows/backend-test.yml
  .github/workflows/frontend-deploy-release.yml
  .github/workflows/frontend-test.yml
  .github/workflows/snapshot.yml
  README.md
Labels: bug, frontend, backend, chore

#330 fix: build branch instead of commit that triggered build event
  .github/workflows/bump.yml
  .github/workflows/frontend-build.yml
  .github/workflows/pull-request.yml
  README.md
Labels: bug, frontend, backend, chore

#331 fix: fetch latest before building snapshot
  .github/workflows/frontend-build.yml
Labels: bug, frontend, backend, chore

#332 chore: build snapshot as part of bump job
  .github/workflows/frontend-build.yml
  .github/workflows/snapshot.yml
Labels: bug, frontend, backend, chore

#335 One more snapshot workflow fix attempt
  .github/workflows/snapshot.yml
Labels: bug, frontend, backend, chore

#336 last fix for real this time
  .github/workflows/snapshot.yml
Labels: bug, frontend, backend, chore

#337 fix: Disable edit event inputs for non-active events + fix hidden 'ready to settle' text for mobile
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
Labels: bug, frontend
