Repository pudding-tech/mikane, pull requests merged in 2023-06, with the labels that each got.

#139 Mobile layout - expenses
  app/pudding-debt/src/app/app.component.html
  app/pudding-debt/src/app/app.component.scss
  app/pudding-debt/src/app/features/mobile/expense-item/expense-item.component.html
  app/pudding-debt/src/app/features/mobile/expense-item/expense-item.component.scss
  app/pudding-debt/src/app/features/mobile/expense-item/expense-item.component.spec.ts
  app/pudding-debt/src/app/features/mobile/expense-item/expense-item.component.ts
  app/pudding-debt/src/app/features/split-button/split-button.component.scss
  app/pudding-debt/src/app/pages/events/event/event.component.html
  app/pudding-debt/src/app/pages/events/event/event.component.ts
  app/pudding-debt/src/app/pages/events/events.component.html
  app/pudding-debt/src/app/pages/events/events.component.scss
  app/pudding-debt/src/app/pages/expenditures/expenditures.component.html
  app/pudding-debt/src/app/pages/expenditures/expenditures.component.scss
  app/pudding-debt/src/app/pages/expenditures/expenditures.component.ts
  app/pudding-debt/src/styles.scss
Labels: frontend, feature

#142 make split button a generic component
  app/mikane/src/app/features/menu/menu.component.html
  app/mikane/src/app/features/menu/menu.component.scss
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.html
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.scss
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.spec.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.directive.spec.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.directive.ts
  app/mikane/src/app/features/split-button/split-button.component.html
  app/mikane/src/app/features/split-button/split-button.component.scss
  app/mikane/src/app/features/split-button/split-button.component.ts
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/pages/settings/settings.component.ts
  app/mikane/src/app/pages/settings/user/user-settings.component.ts
  app/mikane/src/app/pages/user/expense.datasource.ts
  app/mikane/src/app/pages/user/user-dialog/user-dialog.component.ts
  app/mikane/src/app/services/event/event.service.ts
  app/mikane/src/app/services/expense/expense.service.spec.ts
  app/mikane/tsconfig.json
Labels: priority, frontend, improvement

#143 Mobile layout - events
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/features/mobile/event-item/event-item.component.scss
  app/mikane/src/app/features/mobile/event-item/event-item.component.spec.ts
  app/mikane/src/app/features/mobile/event-item/event-item.component.ts
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.scss
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/styles.scss
Labels: frontend, feature

#146 add missing add event button for mobile events page
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.scss
Labels: bug, frontend

#151 Error handler for invalid JSON in body
  server/db_scripts/db_init.sh
  server/src/server.ts
Labels: backend, improvement

#153 Improve DB container initialization
  server/.env.example
  server/bash_scripts/db_init.sh
  server/bash_scripts/entrypoint.sh
  server/bash_scripts/wait-until.sh
  server/db_scripts/db_init.sh
  server/docker-compose.yml
  server/src/dbConfig.ts
  server/src/env.ts
Labels: backend, chore, improvement
