Repository pudding-tech/mikane, pull requests merged in 2023-07, with the labels that each got.

#158 Mobile layout - event navbar
  app/mikane/src/app/features/footer/footer.component.html
  app/mikane/src/app/features/footer/footer.component.ts
  app/mikane/src/app/features/mobile/mobile-navbar/mobile-navbar.component.html
  app/mikane/src/app/features/mobile/mobile-navbar/mobile-navbar.component.scss
  app/mikane/src/app/features/mobile/mobile-navbar/mobile-navbar.component.spec.ts
  app/mikane/src/app/features/mobile/mobile-navbar/mobile-navbar.component.ts
  app/mikane/src/app/features/split-button/split-button.component.html
  app/mikane/src/app/features/split-button/split-button.component.scss
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.scss
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/settings/settings.component.html
  app/mikane/src/app/pages/settings/settings.component.ts
  app/mikane/src/styles.scss
Labels: frontend, improvement

#160 add sorting to expense table
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/services/expense/expense.service.ts
  server/bash_scripts/db_init.sh
  server/bash_scripts/entrypoint.sh
  server/bash_scripts/wait-until.sh
  server/src/parsers/parseExpenses.ts
  server/src/types/types.ts
Labels: frontend, improvement

#161 add admin check for expense delete button
  .vscode/settings.json
  app/mikane/angular.json
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
Labels: frontend, improvement

#163 open category with current weight and only allow numbers
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
  app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.html
  app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.ts
Labels: frontend, improvement

#164 preselect current user as payer when creating new expense
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
Labels: frontend, improvement

#165 prevent user from submitting invalid event and made description optional
  app/mikane/src/app/pages/events/event-dialog/event-dialog.component.html
  app/mikane/src/app/pages/events/events.component.ts
Labels: bug, frontend, improvement

#166 display correct weights when toggling category weighted
  app/mikane/src/app/pages/category/category.component.ts
Labels: bug, frontend

#167 Mobile layout - login
  app/mikane/src/app/features/footer/footer.component.ts
  app/mikane/src/app/features/mobile/mobile-navbar/mobile-navbar.component.ts
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/login/login.component.html
  app/mikane/src/app/pages/login/login.component.scss
  app/mikane/src/app/pages/login/login.component.ts
Labels: frontend, improvement

#168 use material select when not on mobile
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
  app/mikane/src/app/shared/forms/validators/form-control.pipe.ts
Labels: frontend

#174 set icon form control properly
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
Labels: bug, frontend

#175 add min validation for category user weight
  app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.html
  app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.ts
  app/mikane/src/app/pages/category/category.component.ts
Labels: frontend, improvement

#177 add validation feedback when registering user based on backend response
  app/mikane/src/app/pages/register/register-user.component.html
  app/mikane/src/app/pages/register/register-user.component.ts
Labels: frontend, improvement

#187 Mobile layout - account, register, reset password
  app/mikane/src/app/app-routing.module.ts
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.scss
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.spec.ts
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
  app/mikane/src/app/pages/account/account.component.html
  app/mikane/src/app/pages/account/account.component.scss
  app/mikane/src/app/pages/account/account.component.spec.ts
  app/mikane/src/app/pages/account/account.component.ts
  app/mikane/src/app/pages/account/account.routes.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.html
  app/mikane/src/app/pages/account/change-password/change-password.component.scss
  app/mikane/src/app/pages/account/change-password/change-password.component.spec.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.ts
  app/mikane/src/app/pages/account/user/user-settings.component.html
  app/mikane/src/app/pages/account/user/user-settings.component.scss
  app/mikane/src/app/pages/account/user/user-settings.component.spec.ts
  app/mikane/src/app/pages/account/user/user-settings.component.ts
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/login/login.component.scss
  app/mikane/src/app/pages/register/register-user.component.html
  app/mikane/src/app/pages/register/register-user.component.scss
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/pages/reset-password/reset-password.component.html
  app/mikane/src/app/pages/reset-password/reset-password.component.scss
  app/mikane/src/app/pages/reset-password/reset-password.component.ts
  app/mikane/src/app/pages/settings/change-password/change-password.component.html
  app/mikane/src/app/pages/settings/change-password/change-password.component.scss
  app/mikane/src/app/pages/settings/settings.routes.ts
  app/mikane/src/app/pages/settings/user/user-settings.component.html
  app/mikane/src/app/pages/settings/user/user-settings.component.scss
  app/mikane/src/styles.scss
Labels: frontend, feature

#195 iOS specific styling
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.scss
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.scss
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/services/context/context.service.ts
Labels: frontend, improvement

#194 Number of expenses per user
  server/src/api.json
  server/src/db/dbEvents.ts
  server/src/email-services/sendEmail.ts
  server/src/parsers/parseEvents.ts
  server/src/types/types.ts
Labels: backend, feature

#199 Various backend improvements
  .gitattributes
  server/db_scripts/get_expenses.sql
  server/db_scripts/new_expense.sql
  server/db_scripts/remove_user_from_event.sql
  server/src/api.json
  server/src/db/dbEvents.ts
  server/src/db/dbUsers.ts
  server/src/parsers/parseExpenses.ts
  server/src/parsers/parseUsers.ts
  server/src/types/errorCodes.ts
  server/src/types/typesDB.ts
  server/tests/events.test.ts
Labels: backend, improvement

#200 Mobile layout - participants
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.html
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.scss
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.scss
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.scss
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.spec.ts
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/user/user.component.html
  app/mikane/src/app/pages/user/user.component.scss
  app/mikane/src/app/pages/user/user.component.ts
  app/mikane/src/app/services/user/user.service.ts
  app/mikane/src/manifest.webmanifest
  app/mikane/src/styles.scss
Labels: frontend, feature

#201 Better display names + API coverage
  .github/workflows/api.yml
  server/db_scripts/get_users.sql
  server/db_scripts/get_users_name.sql
  server/package-lock.json
  server/package.json
  server/src/db/dbCategories.ts
  server/src/db/dbExpenses.ts
  server/src/parsers/parseCategories.ts
  server/src/parsers/parseExpenses.ts
  server/src/parsers/parseUsers.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/src/utils/setDisplayNames.ts
  server/src/utils/setUserDisplayNames.ts
  server/test_db/docker-compose-test-db.yml
  server/test_db/master_api_key.sql
  server/test_db/resetDatabase.ts
  server/tests/authentication.test.ts
  server/tests/events.test.ts
  server/tests/expenses.test.ts
  server/tests/users.test.ts
  server/vitest.config.ts
Labels: backend, improvement

#203 show error message on account page if getting user fails
  app/mikane/src/app/pages/account/account.component.html
  app/mikane/src/app/pages/account/account.component.scss
  app/mikane/src/app/pages/account/account.component.ts
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.ts
  app/mikane/src/app/pages/account/user/user-settings.component.ts
Labels: frontend, refactor, improvement

#205 fix error that prevented user editing
  app/mikane/src/app/pages/account/user/user-settings.component.ts
  app/mikane/src/app/services/user/user.service.ts
Labels: bug, frontend

#204 Hide expense table if participant has no expenses
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/events/events.routes.ts
  app/mikane/src/app/pages/participant/expense.datasource.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/participant/participant.routes.ts
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.scss
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.ts
  app/mikane/src/app/pages/user/user.routes.ts
  app/mikane/src/app/services/user/user.service.ts
Labels: frontend, refactor, improvement

#206 only show delete button on participant page expenses if expanded part…
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.ts
Labels: bug, frontend

#208 fix weighted input field vertical alignment
  app/mikane/src/app/pages/category/category.component.html
Labels: bug, frontend

#207 add validation to expense dialog
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
Labels: bug, frontend

#209 Run postgres functions upon container start
  server/bash_scripts/custom-entrypoint.sh
  server/bash_scripts/db_init.sh
  server/bash_scripts/db_run_functions.sh
  server/docker-compose.yml
Labels: backend, improvement

#210 Invite users via email
  server/db_scripts/invalidate_register_account_key.sql
  server/db_scripts/new_register_account_key.sql
  server/db_scripts/verify_register_account_key.sql
  server/package-lock.json
  server/package.json
  server/src/api.json
  server/src/api/authentication.ts
  server/src/api/users.ts
  server/src/db/dbUsers.ts
  server/src/email-services/registerAccount.ts
  server/src/env.ts
  server/src/types/errorCodes.ts
  server/test.env
  server/tests/authentication.test.ts
  server/tests/users.test.ts
  server/vitest.config.ts
Labels: backend, feature

#211 feat: implement invite user page
  app/mikane/src/app/app-routing.module.ts
  app/mikane/src/app/features/menu/menu.component.html
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.html
  app/mikane/src/app/pages/invite/invite.component.html
  app/mikane/src/app/pages/invite/invite.component.scss
  app/mikane/src/app/pages/invite/invite.component.spec.ts
  app/mikane/src/app/pages/invite/invite.component.ts
  app/mikane/src/app/pages/invite/invite.routes.ts
  app/mikane/src/app/pages/login/login.component.html
  app/mikane/src/app/pages/register/register-user.component.html
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/pages/register/register-user.routes.ts
  app/mikane/src/app/pages/reset-password/reset-password.component.html
  app/mikane/src/app/services/context/context.service.ts
  app/mikane/src/app/services/user/user.service.ts
  app/mikane/src/styles.scss
  server/bash_scripts/custom-entrypoint.sh
  server/bash_scripts/db_run_functions.sh
Labels: frontend, feature

#213 feat: Revamp account deletion, and more
  .github/workflows/api.yml
  app/mikane/src/app/services/auth/auth.service.ts
  app/mikane/src/app/services/user/user.service.ts
  server/db_scripts/delete_user.sql
  server/db_scripts/new_delete_account_key.sql
  server/db_scripts/verify_delete_account_key.sql
  server/src/api.json
  server/src/api/authentication.ts
  server/src/api/events.ts
  server/src/api/users.ts
  server/src/db/dbUsers.ts
  server/src/email-services/deleteAccount.ts
  server/src/email-services/passwordReset.ts
  server/src/types/errorCodes.ts
  server/tests/authentication.test.ts
  server/tests/events.test.ts
  server/tests/expenses.test.ts
  server/tests/resetDatabase.ts
  server/tests/setup.ts
  server/tests/users.test.ts
Labels: backend, feature

#215 feat: add auth guards to prevent access
  app/mikane/src/app/app-routing.module.ts
  app/mikane/src/app/app.component.ts
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/events/events.routes.ts
  app/mikane/src/app/pages/invite/invite.component.html
  app/mikane/src/app/pages/invite/invite.component.ts
  app/mikane/src/app/pages/login/login.component.ts
  app/mikane/src/app/services/auth/auth.guard.spec.ts
  app/mikane/src/app/services/auth/auth.guard.ts
  app/mikane/src/app/services/auth/auth.interceptor.ts
  app/mikane/src/app/services/auth/auth.service.ts
  app/mikane/src/app/services/auth/logged-in.guard.spec.ts
  app/mikane/src/app/services/auth/logged-in.guard.ts
  app/mikane/src/main.ts
Labels: frontend, feature

#218 feat: Backend validation endpoints
  server/db_scripts/verify_register_account_key.sql
  server/src/api.json
  server/src/api/categories.ts
  server/src/api/events.ts
  server/src/api/users.ts
  server/src/api/validation.ts
  server/src/db/dbUsers.ts
  server/src/db/dbValidation.ts
  server/src/email-services/deleteAccount.ts
  server/src/server.ts
  server/src/types/errorCodes.ts
  server/src/utils/phoneValidator.ts
  server/tests/users.test.ts
  server/tests/validation.test.ts
Labels: backend, feature

#224 feat: Show user avatars, and more
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.scss
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.scss
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
  app/mikane/src/styles.scss
  server/db_scripts/get_categories.sql
  server/db_scripts/remove_user_from_event.sql
  server/src/api/events.ts
  server/src/db/dbEvents.ts
  server/src/errorHandler.ts
  server/src/parsers/parseCategories.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
Labels: frontend, backend, improvement

#225 Frontend testing
  app/mikane/karma.conf.js
  app/mikane/src/app/pages/category/category.component.spec.ts
  app/mikane/src/app/pages/events/events.component.spec.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/pages/register/register-user.routes.ts
  app/mikane/src/app/services/auth/auth.service.spec.ts
  app/mikane/src/app/services/auth/auth.service.ts
  app/mikane/src/app/services/breakpoint/breakpoint.service.spec.ts
  app/mikane/src/app/services/category/category.service.spec.ts
  app/mikane/src/app/services/category/category.service.ts
  app/mikane/src/app/services/context/context.service.spec.ts
  app/mikane/src/app/services/context/context.service.ts
  app/mikane/src/app/services/event/event.service.spec.ts
  app/mikane/src/app/services/event/event.service.ts
  app/mikane/src/app/services/expense/expense.service.spec.ts
  app/mikane/src/app/services/expense/expense.service.ts
  app/mikane/src/app/services/key-validation/key-validation.service.spec.ts
  app/mikane/src/app/services/key-validation/key-validation.service.ts
  app/mikane/src/app/services/user/user.service.spec.ts
  app/mikane/src/app/services/user/user.service.ts
  app/mikane/src/environments/environment.interface.ts
  app/mikane/src/environments/environment.prod.ts
  app/mikane/src/environments/environment.provider.ts
  app/mikane/src/environments/environment.ts
  app/mikane/src/main.ts
Labels: frontend, test

#226 feat: Endpoints for editing expense/category
  server/db_scripts/edit_category.sql
  server/db_scripts/edit_expense.sql
  server/src/api.json
  server/src/api/categories.ts
  server/src/api/expenses.ts
  server/src/api/validation.ts
  server/src/db/dbCategories.ts
  server/src/db/dbExpenses.ts
  server/src/types/errorCodes.ts
  server/tests/categories.test.ts
  server/tests/expenses.test.ts
  server/tests/validation.test.ts
Labels: backend, feature

#230 refactor: use output and event emitter for split button actions
  app/mikane/src/app/features/menu/menu.component.html
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.html
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.ts
  app/mikane/src/app/features/split-button/split-button.component.html
  app/mikane/src/app/features/split-button/split-button.component.ts
Labels: frontend, refactor

#232 fix: Validation endpoints for editing
  server/src/api.json
  server/src/api/validation.ts
  server/src/db/dbValidation.ts
  server/tests/validation.test.ts
Labels: backend, improvement

#234 feat: Delete user overhaul
  .gitignore
  server/.env.test
  server/db_scripts/add_user_as_event_admin.sql
  server/db_scripts/add_user_to_category.sql
  server/db_scripts/add_user_to_event.sql
  server/db_scripts/delete_user.sql
  server/db_scripts/edit_expense.sql
  server/db_scripts/edit_user.sql
  server/db_scripts/get_categories.sql
  server/db_scripts/get_events.sql
  server/db_scripts/get_expenses.sql
  server/db_scripts/get_user.sql
  server/db_scripts/get_users.sql
  server/db_scripts/get_users_name.sql
  server/db_scripts/new_event.sql
  server/db_scripts/new_expense.sql
  server/db_scripts/new_user.sql
  server/db_scripts/remove_user_as_event_admin.sql
  server/db_scripts/remove_user_from_category.sql
  server/db_scripts/remove_user_from_event.sql
  server/db_scripts/schema/db_schema.sql
  server/src/api/events.ts
  server/src/db/dbCategories.ts
  server/src/db/dbEvents.ts
  server/src/db/dbExpenses.ts
  server/src/db/dbUsers.ts
  server/src/env.ts
  server/src/parsers/parseCategories.ts
  server/src/parsers/parseExpenses.ts
  server/src/parsers/parseUsers.ts
  server/src/types/typesDB.ts
  server/tests/users.test.ts
Labels: bug, backend, improvement

#235 feat: implement async validation
  app/mikane/src/app/pages/account/user/user-settings.component.html
  app/mikane/src/app/pages/account/user/user-settings.component.ts
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/events/event-dialog/event-dialog.component.html
  app/mikane/src/app/pages/events/event-dialog/event-dialog.component.ts
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
  app/mikane/src/app/pages/register/register-user.component.html
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/services/form-validation/form-validation.service.spec.ts
  app/mikane/src/app/services/form-validation/form-validation.service.ts
  app/mikane/src/app/services/key-validation/key-validation.service.ts
  app/mikane/src/app/shared/forms/form-control.pipe.ts
  app/mikane/src/app/shared/forms/validators/async-category-name.validator.ts
  app/mikane/src/app/shared/forms/validators/async-email.validator.ts
  app/mikane/src/app/shared/forms/validators/async-event-name.validator.ts
  app/mikane/src/app/shared/forms/validators/async-phone.validator.ts
  app/mikane/src/app/shared/forms/validators/async-username.validator.ts
Labels: frontend, feature

#236 test: add tests for loggedInGuard and authGuard
  app/mikane/src/app/services/auth/auth.guard.spec.ts
  app/mikane/src/app/services/auth/logged-in.guard.spec.ts
Labels: frontend, test

#237 Mobile layout - categories
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.scss
  app/mikane/src/app/features/mobile/category-item/category-item.component.spec.ts
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/services/category/category.service.ts
Labels: frontend, feature

#238 feat: Mobile layout - invite
  app/mikane/src/app/features/mobile/category-item/category-item.component.scss
  app/mikane/src/app/pages/invite/invite.component.html
  app/mikane/src/app/pages/invite/invite.component.scss
Labels: frontend, feature

#239 feat: Mobile layout - delete account
  app/mikane/src/app/pages/delete-account/delete-account.component.html
  app/mikane/src/app/pages/delete-account/delete-account.component.scss
Labels: frontend, feature

#240 feat: Mobile layout - payments
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.scss
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.spec.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
Labels: frontend, feature

#242 feat: Improve categories page
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
Labels: frontend, improvement

#243 feat: implement category and expense editing
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/services/category/category.service.ts
  app/mikane/src/app/services/expense/expense.service.ts
Labels: frontend, improvement
