Repository pudding-tech/mikane, pull requests merged in 2023-08, with the labels that each got.

#251 feat: Split payments into separate lists
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.scss
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
Labels: frontend, improvement

#254 feat: add sorting to participant list
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.ts
Labels: frontend, improvement

#256 Archive events - backend
  server/db_scripts/add_user_as_event_admin.sql
  server/db_scripts/add_user_to_category.sql
  server/db_scripts/add_user_to_event.sql
  server/db_scripts/delete_category.sql
  server/db_scripts/delete_expense.sql
  server/db_scripts/edit_category.sql
  server/db_scripts/edit_category_weighted_status.sql
  server/db_scripts/edit_event.sql
  server/db_scripts/edit_expense.sql
  server/db_scripts/edit_user_weight.sql
  server/db_scripts/get_event_by_name.sql
  server/db_scripts/get_events.sql
  server/db_scripts/get_users.sql
  server/db_scripts/new_category.sql
  server/db_scripts/new_event.sql
  server/db_scripts/new_expense.sql
  server/db_scripts/remove_user_as_event_admin.sql
  server/db_scripts/remove_user_from_category.sql
  server/db_scripts/remove_user_from_event.sql
  server/src/api.json
  server/src/api/events.ts
  server/src/db/dbCategories.ts
  server/src/db/dbEvents.ts
  server/src/db/dbExpenses.ts
  server/src/parsers/parseEvents.ts
  server/src/parsers/parseUsers.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/tests/categories.test.ts
  server/tests/events.test.ts
  server/tests/expenses.test.ts
Labels: backend, feature

#259 feat: Split events into active and archived sections
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/services/event/event.service.ts
Labels: frontend, improvement

#261 test: add test for login page
  app/mikane/src/app/helpers/test.helpers.ts
  app/mikane/src/app/pages/login/login.component.html
  app/mikane/src/app/pages/login/login.component.spec.ts
  app/mikane/src/app/pages/login/login.component.ts
Labels: frontend, test

#262 feat: add user improvements
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.ts
Labels: frontend, improvement

#264 feat: Event settings page
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.guard.ts
  app/mikane/src/app/pages/event-settings/event-settings.routes.ts
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.scss
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/events/events.routes.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/services/event/event.service.ts
Labels: frontend, feature

#266 feat: User deletion improvements
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  server/db_scripts/delete_event.sql
  server/db_scripts/delete_user.sql
  server/db_scripts/delete_user_from_event.sql
  server/db_scripts/get_user.sql
  server/db_scripts/schema/db_schema.sql
  server/src/api/expenses.ts
  server/src/api/users.ts
  server/src/db/dbEvents.ts
  server/src/db/dbUsers.ts
  server/src/types/errorCodes.ts
  server/tests/events.test.ts
  server/tests/users.test.ts
Labels: bug, frontend, backend, improvement

#270 feat: add filter to expense table
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
Labels: frontend, improvement

#271 feat: Profile page
  app/mikane/package-lock.json
  app/mikane/package.json
  app/mikane/src/app/app-routing.module.ts
  app/mikane/src/app/features/menu/menu.component.html
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/app/pages/profile/profile.component.scss
  app/mikane/src/app/pages/profile/profile.component.spec.ts
  app/mikane/src/app/pages/profile/profile.component.ts
  app/mikane/src/app/pages/profile/profile.routes.ts
  app/mikane/src/styles.scss
Labels: frontend, feature

#275 fix: nav bar link not active when expense filtered
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
Labels: bug, frontend

#276 feat: hide buttons and actions when event is archived
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.ts
Labels: frontend, improvement

#282 feat: Different avatars for users and guests
  server/src/parsers/parseCategories.ts
  server/src/parsers/parseExpenses.ts
  server/src/parsers/parseUsers.ts
  server/src/types/types.ts
Labels: backend, improvement

#284 feat: Mobile layout - Profile
  app/mikane/src/app/features/menu/menu.component.html
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/app/pages/profile/profile.component.scss
Labels: frontend, feature

#285 fix: Edit category and expense issues
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.scss
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
Labels: bug, frontend

#286 feat: Expense page (mobile)
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.html
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.scss
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.ts
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.routes.ts
  app/mikane/src/app/pages/expenditures/expense/expense.component.html
  app/mikane/src/app/pages/expenditures/expense/expense.component.scss
  app/mikane/src/app/pages/expenditures/expense/expense.component.spec.ts
  app/mikane/src/app/pages/expenditures/expense/expense.component.ts
  app/mikane/src/app/services/expense/expense.service.ts
Labels: frontend, feature

#288 feat: prefill guest user info when registering a guest user
  app/mikane/src/app/pages/invite/invite.component.html
  app/mikane/src/app/pages/invite/invite.component.ts
  app/mikane/src/app/pages/register/register-user.component.html
  app/mikane/src/app/pages/register/register-user.component.spec.ts
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/pages/register/register-user.routes.ts
  app/mikane/src/app/services/key-validation/key-validation.service.ts
Labels: frontend, improvement

#290 fix: Improve backend build
  .github/workflows/api-staging.yml
  server/package-lock.json
  server/package.json
Labels: backend, improvement

#291 chore: create frontend build and deploy workflow
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-bump.yml
  .github/workflows/frontend-deploy-release.yml
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-staging.yml
  .github/workflows/frontend-test.yml
  .github/workflows/frontend.yml
  .github/workflows/pull-request.yml
Labels: frontend, chore

#292 test: add frontend tests
  app/mikane/package-lock.json
  app/mikane/package.json
  app/mikane/src/app/pages/reset-password/reset-password.component.spec.ts
  app/mikane/src/app/services/auth/auth.service.spec.ts
  app/mikane/src/app/services/category/category.service.spec.ts
  app/mikane/src/app/services/category/category.service.ts
  app/mikane/src/app/services/event/event.service.spec.ts
  app/mikane/src/app/services/expense/expense.service.spec.ts
  app/mikane/src/app/services/form-validation/form-validation.service.spec.ts
  app/mikane/src/app/services/message/message.service.spec.ts
  app/mikane/src/app/shared/forms/form-control.pipe.spec.ts
Labels: frontend, test
