Repository pudding-tech/mikane, pull requests merged in 2024-06, with the labels that each got.

#349 feat: Backend support for user preferences
  server/db_scripts/convert_guest_to_user.sql
  server/db_scripts/edit_guest_user.sql
  server/db_scripts/edit_user.sql
  server/db_scripts/edit_user_preferences.sql
  server/db_scripts/get_user.sql
  server/db_scripts/get_users.sql
  server/db_scripts/new_guest_user.sql
  server/db_scripts/new_user.sql
  server/db_scripts/schema/2.2-2.3_migrations.sql
  server/db_scripts/schema/db_schema.sql
  server/package-lock.json
  server/package.json
  server/src/api.json
  server/src/api/users.ts
  server/src/api/validation.ts
  server/src/db/dbUsers.ts
  server/src/parsers/parseUsers.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/tests/resetDatabase.ts
  server/tests/users.test.ts
  server/tests/validation.test.ts
Labels: backend, feature

#352 fix: Remove sensitive user information from responses including user data
  server/src/api.json
  server/src/api/events.ts
  server/src/api/users.ts
  server/src/parsers/parseUserInfo.ts
Labels: backend, improvement

#353 fix: Restrict editing/deleting user data to signed-in user
  server/src/api/users.ts
  server/src/types/errorCodes.ts
  server/tests/users.test.ts
Labels: backend, improvement

#354 chore: update action dependencies
  .github/workflows/backend-build.yml
  .github/workflows/backend-deploy.yml
  .github/workflows/backend-test.yml
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-test.yml
  .github/workflows/snapshot.yml
Labels: chore, dependencies

#355 track by id
  .github/workflows/snapshot.yml
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
  app/mikane/src/app/features/split-button/split-button.component.html
  app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/event-info/event-info.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.html
  app/mikane/src/app/pages/guests/guests.component.html
  app/mikane/src/app/pages/invite/invite.component.html
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/services/message/success/success-message.component.ts
Labels: bug, frontend

#356 feat: Preferences on account page
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/pages/account/account.component.html
  app/mikane/src/app/pages/account/account.component.ts
  app/mikane/src/app/pages/account/preferences/preferences.component.html
  app/mikane/src/app/pages/account/preferences/preferences.component.scss
  app/mikane/src/app/pages/account/preferences/preferences.component.spec.ts
  app/mikane/src/app/pages/account/preferences/preferences.component.ts
  app/mikane/src/app/pages/account/user/user-settings.component.html
  app/mikane/src/app/pages/account/user/user-settings.component.ts
  app/mikane/src/app/pages/event-info/event-info.component.html
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/services/user/user.service.ts
  app/mikane/src/styles.scss
Labels: frontend, feature

#359 feat: Navigate to user profiles
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/pages/account/user/user-settings.component.html
  app/mikane/src/app/pages/account/user/user-settings.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/category/category.component.scss
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/expenditures/expense/expense.component.html
  app/mikane/src/app/pages/expenditures/expense/expense.component.scss
  app/mikane/src/app/pages/expenditures/expense/expense.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.scss
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/app/services/category/category.service.ts
  server/src/api.json
  server/src/parsers/parseCategories.ts
  server/src/types/types.ts
Labels: frontend, backend, feature

#360 feat: use mat slide toggle for user preferences
  app/mikane/src/app/pages/account/preferences/preferences.component.html
  app/mikane/src/app/pages/account/preferences/preferences.component.spec.ts
  app/mikane/src/app/pages/account/preferences/preferences.component.ts
Labels: frontend, feature

#361 chore: use correct backend artifact for snapshot deploy
  .github/workflows/snapshot.yml
Labels: bug, backend, chore

#362 chore: use token instead of env variable for codecov upload
  .github/workflows/frontend-test.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: bug, frontend, chore

#363 chore: enable automatic deploy for all environments
  .github/workflows/backend-deploy.yml
Labels: backend, chore

#365 feat: Phone number in payments
  README.md
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.scss
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.spec.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.scss
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
  app/mikane/src/assets/mikane_name.svg
Labels: frontend, improvement

#366 feat: Private events
  README.md
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/pages/account/preferences/preferences.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
  app/mikane/src/app/services/event/event.service.spec.ts
  app/mikane/src/app/services/event/event.service.ts
  server/db_scripts/add_user_as_event_admin.sql
  server/db_scripts/add_user_to_category.sql
  server/db_scripts/add_user_to_event.sql
  server/db_scripts/delete_category.sql
  server/db_scripts/delete_event.sql
  server/db_scripts/delete_expense.sql
  server/db_scripts/edit_category.sql
  server/db_scripts/edit_category_weighted_status.sql
  server/db_scripts/edit_event.sql
  server/db_scripts/edit_expense.sql
  server/db_scripts/edit_user_weight.sql
  server/db_scripts/get_categories.sql
  server/db_scripts/get_event_by_name.sql
  server/db_scripts/get_events.sql
  server/db_scripts/get_expenses.sql
  server/db_scripts/get_users.sql
  server/db_scripts/new_category.sql
  server/db_scripts/new_event.sql
  server/db_scripts/remove_user_as_event_admin.sql
  server/db_scripts/remove_user_from_category.sql
  server/db_scripts/remove_user_from_event.sql
  server/package-lock.json
  server/package.json
  server/src/api/categories.ts
  server/src/api/events.ts
  server/src/api/expenses.ts
  server/src/api/users.ts
  server/src/db/dbCategories.ts
  server/src/db/dbEvents.ts
  server/src/db/dbExpenses.ts
  server/src/db/dbGuestUsers.ts
  server/src/db/dbUsers.ts
  server/src/middlewares/authCheck.ts
  server/src/types/errorCodes.ts
  server/src/types/express.d.ts
  server/tests/events.test.ts
  server/tests/expenses.test.ts
  server/tests/guestUsers.test.ts
Labels: frontend, backend, feature

#367 styling: manually serve material icon font
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/pages/event-info/event-info.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/assets/material-icons.woff2
  app/mikane/src/index.html
  app/mikane/src/styles.scss
Labels: frontend, chore, dependencies

#368 feat: Get user by username
  app/mikane/src/app/features/menu/menu.component.spec.ts
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/events/event-dialog/event-dialog.component.html
  app/mikane/src/app/pages/events/event-dialog/event-dialog.component.scss
  app/mikane/src/app/pages/events/event-dialog/event-dialog.component.ts
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/expenditures/expense/expense.component.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
  app/mikane/src/app/pages/profile/profile.component.ts
  app/mikane/src/app/pages/profile/profile.routes.ts
  app/mikane/src/app/services/event/event.service.spec.ts
  app/mikane/src/app/services/event/event.service.ts
  app/mikane/src/app/services/user/user.service.spec.ts
  app/mikane/src/app/services/user/user.service.ts
  server/db_scripts/get_user.sql
  server/src/api.json
  server/src/api/users.ts
  server/tests/users.test.ts
Labels: frontend, backend, improvement

#370 feat: Improved profile page
  app/mikane/angular.json
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/login/login.component.html
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/app/pages/profile/profile.component.scss
  app/mikane/src/app/pages/profile/profile.component.ts
  app/mikane/src/app/services/expense/expense.service.ts
  app/mikane/src/app/services/user/user.service.spec.ts
  app/mikane/src/app/services/user/user.service.ts
  server/db_scripts/delete_event.sql
  server/db_scripts/delete_expense.sql
  server/db_scripts/edit_event.sql
  server/db_scripts/edit_expense.sql
  server/db_scripts/get_events.sql
  server/db_scripts/get_events_for_user.sql
  server/db_scripts/get_expenses.sql
  server/db_scripts/new_expense.sql
  server/package-lock.json
  server/package.json
  server/src/api.json
  server/src/api/categories.ts
  server/src/api/events.ts
  server/src/api/expenses.ts
  server/src/api/guestUsers.ts
  server/src/api/users.ts
  server/src/db/dbCategories.ts
  server/src/db/dbEvents.ts
  server/src/db/dbExpenses.ts
  server/src/db/dbGuestUsers.ts
  server/src/db/dbUsers.ts
  server/src/db/dbValidation.ts
  server/src/parsers/parseExpenses.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/tests/events.test.ts
  server/tests/expenses.test.ts
Labels: frontend, backend, improvement

#377 fix: Change event term 'archived' to 'settled', and other improvements
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.html
  app/mikane/src/app/pages/category/category.component.spec.ts
  app/mikane/src/app/pages/event-info/event-info.component.html
  app/mikane/src/app/pages/event-info/event-info.component.scss
  app/mikane/src/app/pages/event-info/event-info.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/events/events.component.scss
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.html
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/app/services/event/event.service.ts
  app/mikane/src/app/services/user/user.service.ts
  server/db_scripts/add_user_as_event_admin.sql
  server/db_scripts/delete_event.sql
  server/db_scripts/delete_user_from_event.sql
  server/db_scripts/schema/2.2-2.3_migrations.sql
  server/db_scripts/schema/db_schema.sql
  server/package-lock.json
  server/package.json
  server/src/types/enums.ts
  server/src/types/errorCodes.ts
  server/tests/events.test.ts
  server/tests/users.test.ts
  server/vitest.config.mts
Labels: bug, frontend, backend, improvement

#378 feat: Improve event info page, and more
  app/mikane/src/app/features/confirm-dialog/confirm-dialog.component.html
  app/mikane/src/app/features/confirm-dialog/confirm-dialog.component.ts
  app/mikane/src/app/features/mobile/category-item/category-item.component.html
  app/mikane/src/app/features/mobile/category-item/category-item.component.spec.ts
  app/mikane/src/app/features/mobile/category-item/category-item.component.ts
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/features/mobile/event-item/event-item.component.ts
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.html
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.spec.ts
  app/mikane/src/app/features/mobile/expense-item/expense-item.component.ts
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.spec.ts
  app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.spec.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.html
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.spec.ts
  app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.ts
  app/mikane/src/app/features/split-button/split-button.component.ts
  app/mikane/src/app/pages/category/category.component.html
  app/mikane/src/app/pages/event-info/event-info.component.html
  app/mikane/src/app/pages/event-info/event-info.component.scss
  app/mikane/src/app/pages/event-info/event-info.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/events/event/event.component.html
  app/mikane/src/app/pages/events/event/event.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.scss
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/styles.scss
Labels: frontend, improvement

#379 fix: Add outlined passkey icon
  app/mikane/src/app/app.component.ts
  app/mikane/src/app/features/mobile/event-item/event-item.component.html
  app/mikane/src/app/pages/events/events.component.html
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/assets/icons/passkey_outlined.svg
  app/mikane/src/styles.scss
Labels: bug, frontend
