Repository pudding-tech/mikane, pull requests merged in 2024-07, with the labels that each got.

#381 feat: Expense dates
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.scss
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.html
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/expenditures/expense/expense.component.html
  app/mikane/src/app/pages/expenditures/expense/expense.component.scss
  app/mikane/src/app/pages/expenditures/expense/expense.component.ts
  app/mikane/src/app/pages/participant/expense.datasource.spec.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/profile/profile.component.html
  app/mikane/src/app/services/expense/expense.service.spec.ts
  app/mikane/src/app/services/expense/expense.service.ts
  app/mikane/src/styles.scss
  server/db_scripts/edit_expense.sql
  server/db_scripts/get_expenses.sql
  server/db_scripts/new_expense.sql
  server/db_scripts/remove_user_from_event.sql
  server/db_scripts/schema/2.2-2.3_migrations.sql
  server/db_scripts/schema/db_schema.sql
  server/src/api.json
  server/src/api/authentication.ts
  server/src/api/expenses.ts
  server/src/db/dbExpenses.ts
  server/src/parsers/parseCategories.ts
  server/src/parsers/parseEvents.ts
  server/src/parsers/parseExpenses.ts
  server/src/parsers/parseUsers.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/src/types/typesDB.ts
  server/src/utils/dateCreator.ts
  server/tests/expenses.test.ts
Labels: frontend, backend, feature

#383 feat: navigate to event list if trying to access private event
  app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.html
  app/mikane/src/app/pages/login/login.component.html
  app/mikane/src/app/services/auth/auth.interceptor.ts
  server/docker-compose.yml
Labels: frontend, feature

#382 feat: Functionality for sending event ready-to-settle emails
  app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.html
  app/mikane/src/app/pages/account/change-password/change-password.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/participant/participant.component.html
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/register/register-user.component.html
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/services/event/event.service.ts
  server/package-lock.json
  server/package.json
  server/src/api.json
  server/src/api/authentication.ts
  server/src/api/notifications.ts
  server/src/api/users.ts
  server/src/email-services/deleteAccount.ts
  server/src/email-services/notifications/readyToSettle.ts
  server/src/email-services/passwordReset.ts
  server/src/email-services/registerAccount.ts
  server/src/env.ts
  server/src/server.ts
  server/src/types/errorCodes.ts
  server/src/utils/validators/passwordValidator.ts
  server/test_db/docker-compose-test-db.yml
  server/tests/authentication.test.ts
  server/tests/guestUsers.test.ts
  server/tests/notifications.test.ts
  server/tests/validation.test.ts
Labels: frontend, backend, feature

#387 chore: bump angular
  app/mikane/package-lock.json
  app/mikane/package.json
Labels: frontend, chore

#389 fix: can't edit expense
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
Labels: bug, frontend
