Repository pudding-tech/mikane, pull requests merged in 2025-08, with the labels that each got.

#419 feat: Add expand/collapse buttons to mobile payments page
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.spec.ts
  app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.html
  app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
  app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
  app/mikane/src/app/pages/reset-password/reset-password.component.scss
  app/mikane/src/app/services/event/event.service.ts
  app/mikane/src/manifest.webmanifest
  server/package-lock.json
  server/package.json
Labels: frontend, feature

#421 feat: Implement 'add expenses reminder' email
  app/mikane/src/app/pages/event-settings/event-settings.component.html
  app/mikane/src/app/pages/event-settings/event-settings.component.scss
  app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
  app/mikane/src/app/services/event/event.service.spec.ts
  app/mikane/src/app/services/event/event.service.ts
  server/src/api/notifications.ts
  server/src/email-services/notifications/addExpensesReminder.ts
  server/src/types/errorCodes.ts
  server/tests/notifications.test.ts
Labels: frontend, backend, feature

#424 chore: Update backend packages
  server/package-lock.json
  server/package.json
Labels: backend, chore

#429 feat: implement log service to consolidate error logging
  app/mikane/eslint.config.mjs
  app/mikane/src/app/features/menu/menu.component.spec.ts
  app/mikane/src/app/features/menu/menu.component.ts
  app/mikane/src/app/pages/account/account.component.spec.ts
  app/mikane/src/app/pages/account/account.component.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.spec.ts
  app/mikane/src/app/pages/account/change-password/change-password.component.ts
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.spec.ts
  app/mikane/src/app/pages/account/danger-zone/danger-zone.component.ts
  app/mikane/src/app/pages/account/preferences/preferences.component.spec.ts
  app/mikane/src/app/pages/account/preferences/preferences.component.ts
  app/mikane/src/app/pages/account/user/user-settings.component.spec.ts
  app/mikane/src/app/pages/account/user/user-settings.component.ts
  app/mikane/src/app/pages/category/category.component.spec.ts
  app/mikane/src/app/pages/category/category.component.ts
  app/mikane/src/app/pages/delete-account/delete-account.component.ts
  app/mikane/src/app/pages/delete-account/delete-account.routes.ts
  app/mikane/src/app/pages/event-info/event-info.component.spec.ts
  app/mikane/src/app/pages/event-info/event-info.component.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
  app/mikane/src/app/pages/event-settings/event-settings.component.ts
  app/mikane/src/app/pages/events/events.component.spec.ts
  app/mikane/src/app/pages/events/events.component.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.spec.ts
  app/mikane/src/app/pages/expenditures/expenditures.component.ts
  app/mikane/src/app/pages/expenditures/expense/expense.component.ts
  app/mikane/src/app/pages/guests/guests.component.ts
  app/mikane/src/app/pages/invite/invite.component.ts
  app/mikane/src/app/pages/login/login.component.spec.ts
  app/mikane/src/app/pages/login/login.component.ts
  app/mikane/src/app/pages/participant/participant.component.spec.ts
  app/mikane/src/app/pages/participant/participant.component.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
  app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
  app/mikane/src/app/pages/profile/profile.component.ts
  app/mikane/src/app/pages/register/register-user.component.ts
  app/mikane/src/app/pages/register/register-user.routes.ts
  app/mikane/src/app/pages/reset-password/reset-password.component.spec.ts
  app/mikane/src/app/pages/reset-password/reset-password.component.ts
  app/mikane/src/app/services/log/error-handler.ts
  app/mikane/src/app/services/log/log-level.config.ts
  app/mikane/src/app/services/log/log.service.spec.ts
  app/mikane/src/app/services/log/log.service.ts
  app/mikane/src/main.ts
Labels: frontend, feature

#430 chore: add action for automatically creating draft releases
  .github/workflows/draft-release.yml
Labels: chore

#432 chore: combine frontend and backend deploy
  .github/workflows/call_deploy.yml
  .github/workflows/deploy-tag.yml
  .github/workflows/deploy.yml
  .github/workflows/snapshot.yml
Labels: chore

#437 feat: Implement log endpoint
  server/db_scripts/log_client_to_db.sql
  server/db_scripts/log_server_to_db.sql
  server/db_scripts/schema/2.4-2.5_migrations.sql
  server/db_scripts/schema/db_schema.sql
  server/src/api.json
  server/src/api/log.ts
  server/src/db/dbLog.ts
  server/src/env.ts
  server/src/middlewares/dbLogger.ts
  server/src/server.ts
  server/src/types/errorCodes.ts
  server/src/types/types.ts
  server/tests/log.test.ts
  server/tests/resetDatabase.ts
Labels: backend, feature

#463 feat: Implement server CSRF protection
  README.md
  server/.env.example
  server/db_scripts/log_server_to_db.sql
  server/db_scripts/schema/2.4-2.5_migrations.sql
  server/db_scripts/schema/db_schema.sql
  server/package-lock.json
  server/package.json
  server/src/api.json
  server/src/api/authentication.ts
  server/src/api/categories.ts
  server/src/api/events.ts
  server/src/api/expenses.ts
  server/src/api/guestUsers.ts
  server/src/api/log.ts
  server/src/api/notifications.ts
  server/src/api/users.ts
  server/src/api/validation.ts
  server/src/calculations.ts
  server/src/db/dbLog.ts
  server/src/email-services/notifications/readyToSettle.ts
  server/src/env.ts
  server/src/errorHandler.ts
  server/src/middlewares/csrf.ts
  server/src/middlewares/dbLogger.ts
  server/src/middlewares/requestContext.ts
  server/src/server.ts
  server/src/session-store/SessionStore.ts
  server/src/types/errorCodes.ts
  server/tests/mocks/csrfMock.ts
  server/tests/setup.ts
  server/vitest.config.ts
Labels: backend, feature

#465 feat(#460): implement frontend csrf token handling
  app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.spec.ts
  app/mikane/src/app/services/auth/auth.interceptor.spec.ts
  app/mikane/src/app/services/auth/auth.interceptor.ts
  app/mikane/src/app/services/auth/auth.service.spec.ts
  app/mikane/src/app/services/auth/auth.service.ts
  app/mikane/src/app/services/auth/csrf.interceptor.spec.ts
  app/mikane/src/app/services/auth/csrf.interceptor.ts
  app/mikane/src/app/services/log/log.service.ts
  app/mikane/src/app/services/user/user.service.ts
  app/mikane/src/main.ts
Labels: frontend, feature
